# Generated by Django 5.1.6 on 2025-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mobile_verified",
            field=models.BooleanField(default=False),
        ),
    ]
