# Generated by Django 5.1.6 on 2025-04-25 08:41

import storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaintupdate",
            name="proof_image",
            field=models.ImageField(
                storage=storage_backends.MediaStorage(), upload_to="complaint_updates/"
            ),
        ),
    ]
